### ISSUE TITLE
in NetDaemonRxApp application support receiving dynamic yaml in initialize method

### ISSUE THREAD

**Issue by LiranSX** [net-daemon/netdaemon#151]
## The problem
today only a limited YAML structure (sequence/scalar/map) is supported to be used at initialization time of an app which sets properties in the app class. this prevents flexibility and support for more structured/hierarchical data. for example - the following structure is not currently supported:
```
some_app:
  class: "SomeApp.SomeAppRx"
  device_address: 192.168.0.1
  devices:
  - name: "tv"
    commands:
    - name: "command1"
      data: "some code"
    - name: "command2"
      data: "some code2"
```
see YamlConfig.InstanceAndSetPropertyConfig

## The proposed solution
consider using a dynamic type as input to Initialize/InitializeAsync at application start time to contain the entire YAML instead of setting properties - this will allow every structure to be passed as input

## The alternatives
Support hierarchical properties - maybe use automatic deserialization from Yaml to a property with logging messages
