### ISSUE TITLE
Loading entities from nested yaml does not pass deamonApp int constructor

### ISSUE THREAD

**Issue by FrankBakkerNl** [net-daemon/netdaemon#335]
## The problem

when using th efollowing config and property

```yaml
SyncClimateToWindow:
  class: Heating.SyncClimateToWindowApp
    climates:
    - climate.radiator_valve_badkamer
```

```c#

        public IEnumerable<ClimateEntity> Climates { get; set; }
```

The Climates collection gets initialized with one instance of ClimateEntity, but it has its  netDaemonApp field set to null. This causes it to well, not work.

## Environment

- NetDaemon release with the issue:
- Last working NetDaemon release (if known):
- Operating environment (Home assistant Add-on/Docker/Dev setup):
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#

```

## Traceback/Error logs

```txt

```
