### ISSUE TITLE
Subscriptions never trigger for events with a non-int "subtype" event data attribute

### ISSUE THREAD

**Issue by ThomasCulotta** [net-daemon/netdaemon#747]
## The problem

Attempted to set up a basic subscription to the new Hue "relative_rotary" device events added in 2022.9 (link to the event info in the relevant PR https://github.com/home-assistant/core/pull/76758/files#diff-a4e963ebd4fe3bc6ee405068b3a982cfc5c8fe60bac0b0a313956c43abe69d89R55). Native automations in hass of course see the events just fine, but equivalent automations in NetDaemon never proc as if the event is getting lost or thrown out at some point in the pipeline.

## Environment

Home Assistant 2022.9.0
Supervisor 2022.08.5
Operating System 8.5

- NetDaemon release with the issue: 22.34.0
- Last working NetDaemon release (if known): unknown
- Operating environment (Home assistant Add-on/Docker/Dev setup): HA add-on
- Link to integration documentation on our website: https://netdaemon.xyz/docs/v3/hass_model/hass_model_events (I feel like I misunderstand what you want here)

## Link to or paste code that causes the issue

Basic event subscription:
```c#
_HaContext.Events.Filter<Event>("hue_event").Subscribe(Test);
```

Rotary device event example:
```yaml
event_type: hue_event
data:
  device_id: 74d78ecf87da0b833d55d5f894e390c8
  unique_id: fa3d067f-b132-42fa-9cd7-b0ae04bd2ebf
  type: repeat
  subtype: clock_wise
  duration: 400
  steps: 90
origin: LOCAL
time_fired: "2022-09-08T00:27:11.396591+00:00"
context:
  id: 3J7BRP7FKMG4QT50VBCDAW1HTW
  parent_id: null
  user_id: null
```

Minimal repro (manually fire an event through the HASS developer tools "Events" pane with following input)
Event Type: "hue_event"
Event Data: "subtype: clock_wise"

Changing subtype value from clock_wise to any 32-bit integer will cause the event to work correctly in NetDaemon, but setting it to a float or string or setting it beyond an Int32 min/max will repro the bug.

## Traceback/Error logs

This scenario doesn't generate any log messages.
```txt

```
