### ISSUE TITLE
Auto-restart after publish

### ISSUE THREAD

**Issue by dakahler** [net-daemon/netdaemon#800]
It would be nice if the add-on watched the publish directory and automatically restarted itself when a new version is published.

**Comment by Stormalong** [comment]
Agreed. In the meantime I created an Automation that does this.

In configuration.yaml add a folder watcher (change the folder if needed)
```
folder_watcher:
  - folder: /config/netdaemon3

```

Heres the yaml for the automation (you'll probably have to change 'c6a2317c_netdaemon3_1' to whatever the id of your netdaemon addon is).

```
alias: Restart Netdaemon
description: ""
trigger:
  - platform: event
    event_type: folder_watcher
    event_data:
      event_type: closed
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: hassio.addon_restart
    data:
      addon: c6a2317c_netdaemon3_1
mode: restart

```
